# Copyright (C) 2016 Xue Can <xuecan@gmail.com> and contributors.
# Licensed under the MIT license: http://opensource.org/licenses/mit-license

# 由于目前 Python 相关工作不在基于 Python 2，因此不再使用 Homebrew 安装 Python 2 了
# 但仍有一些包如 Pygments、Fabric 等（主要是当做命令行工具使用）是基于 Python 2 的，
# 结合 OS X 内建的 Python 和 easy_install 命令，并安装到 ~/.local 目录中
# 维护 ~/.pydistutils.cfg 文件，通过 user = 1 让 easy_install 只为当前用户安装包，
# 通过环境变量 PYTHONUSERBASE 让包安装到 ~/.local/lib/python/site-packages 中
# (如果没有设置这个环境变量，OS X 下默认按用户安装的路径是 ~/Library/Python/2.7/lib/python/site-packages)
# 配置文件还指定了使用 douban.com 的 pypi 镜像


# install packages in ~/.local/lib/python/site-packages
set -g -x PYTHONUSERBASE "$HOME/.local"


# maintain ~/.pydistutils.cfg
begin
  set -l config_file "$HOME/.pydistutils.cfg"
  echo '
# Do not edit this file directly, as your edits may be overwritten.
# Edit them through fish scripts or by using fish interactively instead.
[easy_install]
user = 1
zip-ok = 0
index-url = http://pypi.douban.com/simple/
' > $config_file
end
